name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test
      - name: Package and Run docker compose
        run: |  # multiple lines to follow
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
         # it tells Docker to stop all services once one container
         # has finished. This will gracefully exit the MySQL container when the main application exits in GitHub Actions.